# SLAM Toolbox Configuration with Increased Buffers
# Optimized for WSL2 and Gazebo simulation

slam_toolbox:
  ros__parameters:
    # ROS Parameters
    odom_frame: chassis_link  # Use chassis_link since no odom frame exists
    map_frame: map
    base_frame: chassis_link
    scan_topic: /scan
    use_map_saver: true
    mode: mapping
    
    # Increased buffer and timeout settings - CRITICAL FOR DROPPING MESSAGES
    transform_timeout: 2.0  # Much longer timeout
    tf_buffer_duration: 120.0  # 2 minutes buffer
    stack_size_to_use: 80000000  # 80MB stack size
    
    # Message Filter Queue Size - THE KEY PARAMETER
    max_laser_range: 12.0
    minimum_time_interval: 0.0  # Process every scan, don't skip
    
    # Processing parameters
    debug_logging: false
    throttle_scans: 1
    transform_publish_period: 0.05  # 20Hz for smoother updates
    map_update_interval: 2.0  # Update map every 2 seconds
    resolution: 0.05
    max_laser_range: 12.0  # Max range for laser
    minimum_time_interval: 0.5  # Minimum time between scans
    minimum_travel_distance: 0.2  # Minimum distance to process
    minimum_travel_heading: 0.2  # Minimum rotation to process
    
    # Scan matcher parameters
    scan_buffer_size: 25  # Increased from default 10
    scan_buffer_maximum_scan_distance: 15.0
    link_match_minimum_response_fine: 0.1  
    link_scan_maximum_distance: 1.5
    loop_search_maximum_distance: 3.0
    do_loop_closing: true 
    loop_match_minimum_chain_size: 10          
    loop_match_maximum_variance_coarse: 3.0  
    loop_match_minimum_response_coarse: 0.35    
    loop_match_minimum_response_fine: 0.45
    
    # Correlation parameters
    correlation_search_space_dimension: 0.5
    correlation_search_space_resolution: 0.01
    correlation_search_space_smear_deviation: 0.1 
    
    # Loop closure parameters  
    loop_search_space_dimension: 8.0
    loop_search_space_resolution: 0.05
    loop_search_space_smear_deviation: 0.03
    
    # Scan matcher
    distance_variance_penalty: 0.5      
    angle_variance_penalty: 1.0    
    
    fine_search_angle_offset: 0.00349     
    coarse_search_angle_offset: 0.349   
    coarse_angle_resolution: 0.0349        
    minimum_angle_penalty: 0.9
    minimum_distance_penalty: 0.5
    use_response_expansion: true

